spring.application.name=auction-house

spring.threads.virtual.enabled=true

# Hide errors stack trace
# spring.web.error.include-stacktrace=never
# logging.level.org.springframework.web=ERROR
# logging.level.org.hibernate=ERROR
# logging.exception-conversion-word=%highlight(%.-500m)%n

# postgresql database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/auction_db
spring.datasource.username=postgres
spring.datasource.password=177013

# generate tables using spring entities and insert values into them then show the queries
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# google
spring.security.oauth2.client.registration.google.client-id=873729029227-4trb1ou8fo90smt4oj4g5svfnemb6ote.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwt.access.expiration=60000
app.jwt.refresh.expiration=120000
app.password.verify.expiration=120000
app.password.reset.expiration=120000
app.fromEmail=hdtsfr84@gmail.com

# user local mailpit service
spring.mail.host=localhost
spring.mail.port=1025

