spring.application.name=auction-house

spring.threads.virtual.enabled=true

# Hide errors stack trace
# spring.web.error.include-stacktrace=never
# logging.level.org.springframework.web=ERROR
# logging.level.org.hibernate=ERROR
# logging.exception-conversion-word=%highlight(%.-500m)%n

# postgresql database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/auction_db
spring.datasource.username=postgres
spring.datasource.password=177013

# generate tables using spring entities and insert values into them then show the queries
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# google
spring.security.oauth2.client.registration.google.client-id=di
spring.security.oauth2.client.registration.google.client-secret==di
spring.security.oauth2.client.registration.google.scope=di,email

# github
spring.security.oauth2.client.registration.github.client-id=Ov23liLEiTLgqLGK9JeD
spring.security.oauth2.client.registration.github.client-secret=a68b26158234ecb0858510f519b9ce301c8cb377
spring.security.oauth2.client.registration.github.scope=read:user,user:email

# facebook
spring.security.oauth2.client.registration.facebook.client-id=di
spring.security.oauth2.client.registration.facebook.client-secret==di
spring.security.oauth2.client.registration.facebook.scope=di,email


# JWT Custom Properties
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# 10 seconds for testing
app.jwt.access.expiration=15000
# 1 minut for testing
app.jwt.refresh.expiration=60000

# email service
spring.mail.host=smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=lusterz
spring.mail.password=test123
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
# from email
app.fromEmail=hdtsfr84@gmail.com

