spring.application.name=auction-house

spring.threads.virtual.enabled=true

# Hide errors stack trace
# spring.web.error.include-stacktrace=never
# logging.level.org.springframework.web=ERROR
# logging.level.org.hibernate=ERROR
# logging.exception-conversion-word=%highlight(%.-500m)%n

# postgresql database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/auction_db
spring.datasource.username=postgres
spring.datasource.password=177013

# generate tables using spring entities and insert values into them then show the queries
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.defer-datasource-initialization=true

# google
spring.security.oauth2.client.registration.google.client-id=873729029227-4trb1ou8fo90smt4oj4g5svfnemb6ote.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

# JWT Custom Properties
app.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
# 10 seconds for testing
app.jwt.access.expiration=25000
# 1 minut for testing
app.jwt.refresh.expiration=60000
# 1 minut for testing
app.jwt.verify.expiration=60000

# email service
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=bd4845a3b439c7
spring.mail.password=3e6029cfa9da84
# from email
app.fromEmail=hdtsfr84@gmail.com

